### ISSUE TITLE
Branded Button with Progress Animation

### ISSUE THREAD

**Issue by maplesyrupsucker** [Bitcoin-com/badger#1]
**What problem are you trying to solve?**
Offer a default branded button with loading animation. Ensure users know they are tipping with Bitcoin Cash. 

Worth considering - add a `<small>` text below button that reads "What is badger button?" which leads users to badger.bitcoin.com to learn more.

**Describe the solution you'd like**
Provide consistent UX to users integrating badger into their projects. 

**Additional context**
Some ideas for inspiration - I think it's worth ensuring the Bitcoin Cash logo is prominently displayed attached or next to the button in some way. 

- https://codepen.io/joshuaward/pen/oGZrWN
- https://tympanus.net/Development/ParticleEffectsButtons/
- https://tympanus.net/Development/ProgressButtonStyles/
- https://tympanus.net/Development/ElasticProgress/
- https://codemyui.com/upload-button-to-progress-indicator-micro-interaction/
- https://codemyui.com/submit-button-loading-animation-click/
- https://codepen.io/juRiii/pen/gibpL
- https://codepen.io/takaneichinose/pen/wRXryM

**Comment by paOol** [comment]
closing due to age.
