### ISSUE TITLE
Badger Button should show proper error message when not logged in

### ISSUE THREAD

**Issue by Ekliptor** [Bitcoin-com/badger#10]
Badger Wallet 0.1.3 in Chrome

When I am not logged in to my wallet (it asks for password when clicking on the icon) and I click on the Badger Button to pay, nothing happens.

Steps to reproduce:
1. logout of badger
2. click on the button in your sample https://github.com/Bitcoin-com/badger-samples/blob/master/badger-button.html
3. nothing happens

It should show a proper error message asking the user to login (just like you redirect him when the wallet is not installed).

**Comment by Ekliptor** [comment]
is there an update to this?
Or can you tell me an API call how to check if the user is logged in? So I can implement it myself.
I don't see anything to directly check if the user is logged in on this object:
`web4bch = new window.Web4Bch(window.web4bch.currentProvider).bch`

**Comment by SpendBCH** [comment]
Right now the best way to check if a user's wallet is locked is checking if web4bch.bch.defaultAccount is undefined or null.

**Comment by paOol** [comment]
closing due to age.
