### ISSUE TITLE
'Reset Wallet' causes "connecting to mainnet" endless spinner

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/badger#103]
From @brentrincker on telegram: 

> I am able to reproduce this with a brand new wallet as well as the two I have actually used. Basically The steps to get the spinning status wheel are 

1. restore a wallet or create a new one 
2. settings > reset account 
3. constant spinning status wheel with message "connecting to mainnet"

**Comment by paOol** [comment]
fixed in v0.6
