### ISSUE TITLE
Allow 3rd party apps to open the 'unlock Badger' dialog directly rather than sending an "please unlock it first" error

### ISSUE THREAD

**Issue by Klakurka** [Bitcoin-com/badger#123]
Allow 3rd party apps to open the 'unlock Badger' dialog directly rather than sending an "please unlock it first" error.

For example, Pay Button displays an alert() when Badger is locked. Better UX would be that the 'enter password' dialog would pop up in badger instead of having to trigger it manually by closing the alert and then clicking on the Badger icon in the browser toolbar.

**Comment by paOol** [comment]
will be addressed in re-write.

closing due to age.
