### ISSUE TITLE
All funds unspendable after importing seed phrase

### ISSUE THREAD

**Issue by OverlordQ** [Bitcoin-com/badger#154]
**Describe the bug**
After importing the seed phrase, no tokens or BCH is allowed to be spent. Errors with:
ALERT: No keyring found for the requested account.

**To Reproduce**
1. Import Phrase
2. Try to spend

**Expected behavior**
Money works

**Screenshots**
https://i.imgur.com/ZEACNJV.png

**Browser details (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Badger Version: 0.7.4

**Additional context**
Tried every balance in the account, none would send. All had same error.

**Comment by paOol** [comment]
we are rolling back a version to prevent this.

will investigate and version bump when we fix this.

**Comment by paOol** [comment]
0.7.6 will have a fix for these issues.

thanks for the report.
