### ISSUE TITLE
Logout Weirdness

### ISSUE THREAD

**Issue by SpicyPete** [Bitcoin-com/badger#158]
2 Issues related to logging out of the app

1. Clicking logout, will automatically log the user back in, making it very difficult to enter a different seed, as the only place to do this is on the login screen.
  * Should not automatically login, rather should provide an option to use the current wallet, import another, or create a new wallet.

2. If the wallet is open in a background tab, and the user logs out from the extension window, they maintain the login within the background tab.  Which could lead to a user think they logged out, and exposing their wallet to other people who use the computer

**Comment by paOol** [comment]
logout fixed in 0.7.6
