### ISSUE TITLE
Feature request: disable ability to send to potential segwit addresses by default

### ISSUE THREAD

**Issue by emergent-reasons** [Bitcoin-com/badger#212]
Reference: https://github.com/Bitcoin-com/Wallet/issues/579

Copy-paste of text:

We continue to get people struggling with BCH sent to segwit addresses, even experienced users. Today we had another one sending to paxful and since paxful reuses addresses, the pubkey was exposed and the money quickly picked up by an unknown miner.

You may know that Electron decided to take action and disable the ability to send to 3xxxx addresses by default although it can be re-enabled for people who know what they are doing. It is documented [here](https://github.com/Electron-Cash/Electron-Cash/issues/1658).

Hope badger will consider the same restriction.

**Comment by paOol** [comment]
legacy addresses will be disabled in the upcoming 0.7.15 release (this monday hopefully).
