### ISSUE TITLE
Add CashAccount support

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/badger#25]
## Summary

Bitcoin Cash's alias/address system that is designed to meet the expectations of normal users. It allows for human readable account names.

Add CashAccount support to Badger.

https://www.cashaccount.info/

**Comment by monsterbitar** [comment]
Should I update the link on the cashaccount.info website to point here, instead of to https://github.com/BadgerWallet/badger/issues/15 ?

Also, volunteering to the best of my ability to help out if there's anything that needs to be done to speed up the process of getting the support merged.

**Comment by paOol** [comment]
implemented
