### ISSUE TITLE
Extension non-functional with Chromium v57 on Debian Linux 

### ISSUE THREAD

**Issue by alwaysAn0n** [Bitcoin-com/badger#28]
**Describe the bug**
For a brand new, first time installation the extension fails to function.  Although it installs just fine, it is completely non-functional for me.  Clicking on the wallet extension icon loads the main popup but the frame is totally empty except for short vertical scrollbar.  I've tried completely reinstalling it but the issue persists.  Inspecting the `background page` view shows a single error `Uncaught SyntaxError: Unexpected token ) at background.js:17487` .  I can't follow it any further though because it refers to a line number that doesn't exist in my source window.  Furthermore, attempting to view the errors/warning on the extension management page freezes the page entirely requiring me to force close the tab.  I expect it's because the script is insanely large (almost 17,000 lines).  

**To Reproduce**
1. Install extension from https://chrome.google.com/webstore/detail/badger-wallet/jadobjbcgibiopkifknkfnohlelpocll/related
2. Click on Badger Wallet extension icon 
3. Confirm main popup is blank

**Expected behavior**
A clear description of what you expected to happen.

**Screenshots**
![badger-fail](https://user-images.githubusercontent.com/34048172/51404866-4f986d80-1b1a-11e9-8008-c1bf4386d824.jpg)

**Browser details (please complete the following information):**
 - OS: Debian Linux 9.5 (64-bit)
 - Browser: Chromium v57.0.2987.98
 - Badger Version:  0.1.3

**Comment by christroutner** [comment]
For perspective I'm on Pop! OS (based on Ubuntu 18.04) running Chromium 71.0.3578.80 with Badger Wallet v0.1.3. Everything seems to be working great.

**Comment by paOol** [comment]
i believe this is resolved now; closing.
