### ISSUE TITLE
When I open a browser and not logged into Badger

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/badger#3]
Open browser not logged into Badger
> Click on a badger Button
> Nothing happens
 > `MetaMask - RPC Error: Error: Invalid from address undefined not a string` in console
> Login to Badger by clicking on the plugin
> Works as expected.

What I expect:
> Open browser not logged into Badger
> Click on a badger Button
> Popup with login prompt (as before)
> Works as expected

**Comment by tbrannt** [comment]
Having a login promt would be super convenient. But opposed to how it was implemented before (I think in 0.0.9) one that does not to actually perform the action that triggered the login promt and then fails doing it would be nice.

**Comment by paOol** [comment]
will be addressed in re-write.

closing due to age.
