### ISSUE TITLE
Inconsistent behavior between Firefox & Chrome when Badger is locked

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/badger#35]
Originally reported by Soupernerd in the Badger Wallet Telegram channel on 1/28/2019:

1. Firefox, when badger button is clicked and badger is locked, still it pops up badger to unlock. It then pushes the tx info and amounts (ideal)

2. Chrome and brave will do nothing if clicking a badger button and badger button is locked. So we put in a check, and alert user to please unlock badger wallet before proceeding. (Not ideal as it adds more required userside interactions)

**Comment by paOol** [comment]
will be addressed in re-write.

closing due to age.
