### ISSUE TITLE
Constant refresh when running Metamask and Badger side-by-side

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/badger#36]
Originally reported by Soupernerd in the Badger Wallet Telegram channel on 1/28/2019:

The following is a test on firefox with metamask active. Notice the constant refreshing. Closing paybutton modal. Initially we thought it was paybutton specific but then tried other "normal" badger buttons and experienced the same. It was sporadic at times, and expected at others:

[https://imgur.com/R9KAXyU](https://imgur.com/R9KAXyU)

The following is firefox without metamask active (seems to work as intended):

[https://imgur.com/FuRjutd](https://imgur.com/FuRjutd)

And just for the sake of it, the following are chrome and brave testing. Similar variables (seem to work as intended):

Chrome:

[https://imgur.com/GORHgnn](https://imgur.com/FuRjutd)

Brave:

[https://imgur.com/ypiRBK9](https://imgur.com/ypiRBK9)

**Comment by paOol** [comment]
this is resolved now.
