### ISSUE TITLE
Selecting Mainnet in Chrome created permanent overlay

### ISSUE THREAD

**Issue by christroutner** [Bitcoin-com/badger#37]
Originally reported by Theo in the Badger Wallet Telegram group on 1/30/2019:

Clicking the button in the Chrome menu bar to open the popover, and then clicking the mainnet button (to see the list of networks, of which there is only mainnet of course), then clicking mainnet from the list...

Produces an overlay saying connecting to mainnet but it never finishes/goes away (even though underneath I can see my balance changes, so the rest is working)

**Comment by theoboyd** [comment]
More version info as requested:
Google Chrome 71.0.3578.98
macOS Mojave 10.14.2

**Comment by cgcardona** [comment]
This has been fixed in latest build.
