### ISSUE TITLE
Badger wallet let me send my full balance with no transaction fee. 

### ISSUE THREAD

**Issue by cgcardona** [Bitcoin-com/badger#4]
**Reported in Telegram 1/10/19 @ 5:12pm PST**

This made the transaction get stuck.

The balance showed on my wallet still but any attempt to transact would show and error of insufficent funds.

I was able to work around this issue by restoring from seed to electron cash new wallet and sending it to another address.

This time it had a fee on it.

Few minutes later, fixed.

My badger wallet still shows a balance that it quite frankly doesn't have anymore though.

**Comment by christroutner** [comment]
So, it looks to me like this may need to be broken out into two issues:

1. A new feature that let's people click a 'send max' button to send everything in their wallet (minus a fee)

2. A bug fix to prevent people from manually putting in their full amount and clicking send. It should prevent this behavior by ensuring there is enough money set aside for a transaction fee.

**Comment by paOol** [comment]
sendmax is enabled, and correct fees are calculated.
