### ISSUE TITLE
Segregate SLP tokens to another account

### ISSUE THREAD

**Issue by m4ktub** [Bitcoin-com/badger#55]
**What problem are you trying to solve?**
Prevent people from unintentinally losing/burning SLP tokens.

**Describe the solution you'd like**
I don't think I have a very good solution but here is a proposal.

Do not mix BCH and SLP in the same account. Badger Wallet would always start with a BCH-only account (`m/44'/145'/0'`). To receive SLP tokens the user would need to create a new SLP-only account. That account (`m/44'/145'/1'`) would only show a `simpleledger:...` address. To fund transfers, for those tokens, Badger Wallet would use the main account `m/44'/145'/0'` (or the first BCH-only account with funds) which avoids having to fund those accounts.

**Additional context**
People may use the same seed on multiple wallets to avoid having multiple backups or to have control over the same balance on multiple wallets. If you receive `simpleledger` tokens with Badger Wallet and import the same see on another wallet you may lose tokens because. To most wallets those ouptuts are regular outputs that may be spent, for example, in a send max operation.

Segregating tokens to another account keeps the wallet BIP44 compliant and hides token outputs from a default import of the same seed on another wallet. You obviously can still override the derivation path to have the SLP accounts imported, for example, to Electron Cash.

**Comment by m4ktub** [comment]
I had assumed that SLP did not have a registered coin type but it has (see [here][1]). This means that, in my previous suggestion, the SLP-only accounts could use the `m/44'/245'/0'` derivation, instead of `m/44'/145'/1'`. This would interact better with other BIP44 multi-account wallets and reduce token loss even further.

[1]: https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by paOol** [comment]
implemented
