### ISSUE TITLE
Multiple badger buttons on the same page can't have different amounts

### ISSUE THREAD

**Issue by Ekliptor** [Bitcoin-com/badger#6]
Tested with Badger: 0.1.2 in Chrome

When I use multiple badger buttons on the same HTML page for my WordPress addon https://cashtippr.com/ they can not have different amounts. I need this feature in some cases. I see no reason why it shouldn't be possible, so I'm assuming a bug.

Steps to reproduce:
1. add a 2nd button with different amount in your sample: https://github.com/Bitcoin-com/badger-samples/blob/master/badger-button.html
2. click on pay - both buttons ask for the same amount :(

**Comment by cgcardona** [comment]
This should be resolved in `badgerButton-1.0.1.js` and `badgerToken-1.0.1.js`

* https://developer.bitcoin.com/badger/badgerButton-1.0.1.js
* https://developer.bitcoin.com/badger/badgerToken-1.0.1.js

https://github.com/Bitcoin-com/badger-samples/blob/master/badger-button.html has been updated as well.
