### ISSUE TITLE
Callback function can not be on a global object

### ISSUE THREAD

**Issue by Ekliptor** [Bitcoin-com/badger#7]
Badger 0.1.2 in Chrome

It's good practice to not pollute the global window context. So it would be cool if Badger would allow the callback function to be part of my main app object (think of an object compiled with WebPack having more functions):
```
	var myApp = {
			pay: function(txid) {
				console.log("PAID", txid);
			}
	}
```

When I use `data-success-callback="myApp.pay"` it fails by saying `window[successCallback] is not a function`.
I know it works with a "normal" global function, so we can classify this between "bug" and "feature request" 😇

**Comment by paOol** [comment]
will be addressed in re-write.

closing due to age.
