### ISSUE TITLE
Feature Request: Button style

### ISSUE THREAD

**Issue by Ekliptor** [Bitcoin-com/badger#8]
For Badger Button and other BCH-based buttons (gateway.cash and more) to be adopted it would be very helpful if you could provide 1 or 2 CSS classes with button styles. Think of the MasterCard, Visa,... logos & buttons on payment pages.

If every website uses its images & styles for the payment button it will
- not immediately be recognized by users
- look less trustworthy

**Comment by paOol** [comment]
will be addressed in re-write.

closing due to age.
