### ISSUE TITLE
Firefox login in add on graphics gone

### ISSUE THREAD

**Issue by dasterdly** [Bitcoin-com/badger#9]
Firefox box extension after login displays a flick of user data and after that it displays white box only! begun after firefox update. tried restarting browser and reboot computer. Still the same issue. 
Thank you

![screen shot 2019-01-12 at 18 02 22](https://user-images.githubusercontent.com/46131124/51076085-4fb8e900-1694-11e9-8412-c31bfcf4e6b7.png)

**Comment by dasterdly** [comment]
Thank you. The firefox inspector, is it at all possible to inspect the element box of the extension icons in the browser above web content?

i will reinstall it.

**Comment by cgcardona** [comment]
@dasterdly is this still an issue?

**Comment by paOol** [comment]
closing, cannot reproduce.
